import type { Contact, Deal, Activity, DashboardMetrics } from "./types"

export const sampleContacts: Contact[] = [
  {
    id: "1",
    name: "John Smith",
    email: "john.smith@techcorp.com",
    phone: "+1 (555) 123-4567",
    company: "TechCorp Inc.",
    position: "CTO",
    tags: ["Enterprise", "Hot Lead"],
    createdAt: "2024-01-15",
    lastActivity: "2024-01-28",
    value: 50000,
  },
  {
    id: "2",
    name: "Sarah Johnson",
    email: "sarah.j@innovate.io",
    phone: "+1 (555) 987-6543",
    company: "Innovate Solutions",
    position: "VP Sales",
    tags: ["Mid-Market", "Qualified"],
    createdAt: "2024-01-10",
    lastActivity: "2024-01-27",
    value: 25000,
  },
  {
    id: "3",
    name: "Michael Chen",
    email: "m.chen@startupx.com",
    phone: "+1 (555) 456-7890",
    company: "StartupX",
    position: "Founder",
    tags: ["Startup", "Cold Lead"],
    createdAt: "2024-01-20",
    lastActivity: "2024-01-26",
    value: 15000,
  },
  {
    id: "4",
    name: "Emily Davis",
    email: "emily.davis@globaltech.com",
    phone: "+1 (555) 321-0987",
    company: "GlobalTech",
    position: "Director of IT",
    tags: ["Enterprise", "Negotiating"],
    createdAt: "2024-01-05",
    lastActivity: "2024-01-29",
    value: 75000,
  },
]

export const sampleDeals: Deal[] = [
  {
    id: "1",
    title: "Enterprise Software License",
    value: 50000,
    probability: 80,
    stage: "negotiation",
    contactId: "1",
    contactName: "John Smith",
    company: "TechCorp Inc.",
    owner: "Alex Thompson",
    createdAt: "2024-01-15",
    closeDate: "2024-02-15",
    description: "Annual enterprise software license for 500 users",
  },
  {
    id: "2",
    title: "Cloud Migration Project",
    value: 25000,
    probability: 60,
    stage: "proposal",
    contactId: "2",
    contactName: "Sarah Johnson",
    company: "Innovate Solutions",
    owner: "Maria Garcia",
    createdAt: "2024-01-10",
    closeDate: "2024-03-01",
    description: "Complete cloud infrastructure migration",
  },
  {
    id: "3",
    title: "Startup Package",
    value: 15000,
    probability: 30,
    stage: "qualified",
    contactId: "3",
    contactName: "Michael Chen",
    company: "StartupX",
    owner: "David Wilson",
    createdAt: "2024-01-20",
    closeDate: "2024-04-01",
    description: "Startup software package with support",
  },
  {
    id: "4",
    title: "Global Implementation",
    value: 75000,
    probability: 90,
    stage: "negotiation",
    contactId: "4",
    contactName: "Emily Davis",
    company: "GlobalTech",
    owner: "Alex Thompson",
    createdAt: "2024-01-05",
    closeDate: "2024-02-28",
    description: "Global software implementation across 10 offices",
  },
]

export const sampleActivities: Activity[] = [
  {
    id: "1",
    type: "call",
    title: "Follow-up call with John Smith",
    description: "Discuss contract terms and implementation timeline",
    contactId: "1",
    dealId: "1",
    contactName: "John Smith",
    dealTitle: "Enterprise Software License",
    dueDate: "2024-01-30",
    completed: false,
    priority: "high",
    createdAt: "2024-01-28",
    owner: "Alex Thompson",
  },
  {
    id: "2",
    type: "email",
    title: "Send proposal to Sarah Johnson",
    description: "Send detailed proposal for cloud migration project",
    contactId: "2",
    dealId: "2",
    contactName: "Sarah Johnson",
    dealTitle: "Cloud Migration Project",
    dueDate: "2024-01-29",
    completed: true,
    priority: "medium",
    createdAt: "2024-01-27",
    owner: "Maria Garcia",
  },
  {
    id: "3",
    type: "meeting",
    title: "Demo session with Michael Chen",
    description: "Product demonstration and Q&A session",
    contactId: "3",
    dealId: "3",
    contactName: "Michael Chen",
    dealTitle: "Startup Package",
    dueDate: "2024-02-01",
    completed: false,
    priority: "medium",
    createdAt: "2024-01-26",
    owner: "David Wilson",
  },
  {
    id: "4",
    type: "task",
    title: "Prepare contract for Emily Davis",
    description: "Draft final contract with negotiated terms",
    contactId: "4",
    dealId: "4",
    contactName: "Emily Davis",
    dealTitle: "Global Implementation",
    dueDate: "2024-01-31",
    completed: false,
    priority: "high",
    createdAt: "2024-01-29",
    owner: "Alex Thompson",
  },
]

export const dashboardMetrics: DashboardMetrics = {
  totalContacts: 1247,
  activeDeals: 23,
  totalRevenue: 2450000,
  monthlyGrowth: 12.5,
  conversionRate: 24.8,
  avgDealSize: 42500,
}
